feat: added middleware for http streaming
stitchng/adonis-extensions pull request #17
Opened 2021-12-11 06:22 UTC by isocroft

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce?

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](https://github.com/stitchng/adonis-extensions/blob/master/CONTRIBUTING.md) doc
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2021-12-11 07:35 UTC, isocroft commented on src/Middleware/StreamResponseBody.js
> +    )
```suggestion
'use strict'

const nodeReq = require('node-req')

class StreamResponseBody {
  constructor (Config) {
    this.chunkedResponse = Config.get('extension.chunkedResponse')
  }

  async handle ({ request, response }, next) {
    const charsets = request.header('Accept-Charset', null)
    response.transform(
      charsets !== null ? nodeReq.charset(
        response.request,
        ['utf-8', 'utf-7', 'iso-8859-1', 'us-ascii', 'base64']
      ) : 'utf-8',
      this.chunkedResponse
    )
```

2021-12-14 00:00 UTC, isocroft commented on src/Middleware/StreamResponseBody.js
> +
```suggestion
  async handle ({ request, response }, next, [ chunked, multipart ]) {
    const accept = request.header('Accept', '')
    const charsets = request.header(
      'Accept-Charset',
      accept.replace(/\b; charset=(.*)$/, function(pattern, substring) {
        return typeof pattern === 'string' ? substring : null
      })
    )

    response.transform(
      nodeReq.charset(
        response.request,
        charsets !== null
          ? charsets.split(', ')
          : ['utf-8', 'utf-7', 'iso-8859-1', 'us-ascii']
      ),
     {
       chunked: (chunked === 'chunked' || multipart === 'chunked' || this.chunkedResponse),
       multipart: (chunked === 'multipart' || multipart === 'multipart')
    )

    /* @HINT: send whitespace chars to client so it (client) doesn't attempt to close connection */
    process.nextTick(() => response.sendToStream('                  '))

```

2021-12-14 21:58 UTC, isocroft commented on src/Middleware/StreamResponseBody.js
> +    )
```suggestion
    const [ , charset ] = request.header('Accept', '').match(/^(?:[^;]+); charset=(.*)\b|$/)
    const charsets = request.header(
      'Accept-Charset',
      charset
    )
```

2021-12-14 22:00 UTC, isocroft commented on src/Middleware/StreamResponseBody.js
> +      charset
```suggestion
      charset || null
```

2021-12-14 22:00 UTC, isocroft commented on src/Middleware/StreamResponseBody.js
> +    )
```suggestion
    })
```

2021-12-15 15:40 UTC, stitchng requested changes

2021-12-15 15:40 UTC, stitchng commented on src/Middleware/StreamResponseBody.js
> +          ? charsets.split(', ')
```suggestion
          ? charsets.toLowerCase().replace(/(?:; ?q=\d\.\d{1,}(\,\*?)?)+\b|$/g, '').replace(',', ', ').split(', ')
```

2021-12-15 15:40 UTC, stitchng commented on src/Middleware/StreamResponseBody.js
> +          : ['utf-8', 'utf-7', 'iso-8859-1', 'us-ascii']
```suggestion
          : ['utf-8', 'utf-7', 'iso-8859-1', 'us-ascii']
```
```suggestion
          : ['utf-8', 'iso-8859-1', 'us-ascii', 'iso-10646-ucs-2', 'utf-7']
```

2021-12-15 15:43 UTC, stitchng requested changes

2021-12-15 15:43 UTC, stitchng commented on src/Middleware/StreamResponseBody.js
> +    const [ , charset ] = request.header('Accept', '').match(/^(?:[^;]+); charset=(.*)\b|$/)
```suggestion
    const [ , charset ] = request.header('Accept', '').match(/^(?:[^;]+); charset=(.*)\b|$/) || ['', false]
```

2021-12-15 15:44 UTC, merged