feat: update response macros
stitchng/adonis-extensions pull request #20
Opened 2021-12-11 06:26 UTC by isocroft

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce?

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](https://github.com/stitchng/adonis-extensions/blob/master/CONTRIBUTING.md) doc
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2021-12-11 07:40 UTC, isocroft commented on providers/ResponseExtensionProvider.js
> +        encoding
```suggestion
        encoding.replace(/^us-/, '')
```

2021-12-11 07:40 UTC, isocroft commented on providers/ResponseExtensionProvider.js
> +        const payload = data instanceof Buffer ? data : Buffer.from(data, encoding)
```suggestion
        const payload = data instanceof Buffer ? data : Buffer.from(data, encoding.replace(/^us-/, ''))
```

2021-12-11 08:21 UTC, isocroft commented on providers/ResponseExtensionProvider.js
> +const nodeRes = require('node-res');
```suggestion
const destroy = require('destroy')
```

2021-12-11 08:21 UTC, isocroft commented on providers/ResponseExtensionProvider.js
> +          error => that.abortIf(true, 500, `Something unexpected happend: ${error.message}`)
```suggestion
          error => that.abortIf(true, error.code === 'ENOENT' ? 404 : 500, `Something unexpected happened: ${error.message}`)
```

2021-12-11 08:21 UTC, isocroft commented on providers/ResponseExtensionProvider.js
> +        nodeRes.stream(that.response, readStream).catch(
```suggestion
        entityBody.stream(that.response, readStream).catch(
```

2021-12-11 08:21 UTC, isocroft commented on providers/ResponseExtensionProvider.js
```suggestion

const entityBody =  {
  stream: function streamer (res, body) {
    return new Promise((resolve, reject) => {
    if (typeof (body.pipe) !== 'function') {
      reject(new Error('[adonisjs-extensions]: cannot find a valid read-stream'))
      return
    }

    let finished = false

    /**
     * Error in stream
     */
    body.on('error', (error) => {
      if (finished) {
        return
      }

      finished = true
      destroy(body)

      reject(error)
    })

    /**
     * Consumed stream
     */
    body.on('end', resolve)

    /**
     * Written response
     */
    onFinished(res, function () {
      finished = true
      destroy(body)
    })

    /**
     * Pipe to res
     */
    body.pipe(res)
  })
  }
}

```

2021-12-11 08:21 UTC, isocroft commented on providers/ResponseExtensionProvider.js
> +          return this._backPressureQueue.shift()
```suggestion
          return this._backPressureQueue.length
            ? this._backPressureQueue.shift()
            : null
```

2021-12-11 08:21 UTC, isocroft commented on providers/ResponseExtensionProvider.js
> +        throw new Error('@adonisjs-extensions: Cannot call `response.sendToStream()` without calling `response.transform()` first')
```suggestion
        throw new Error('[adonisjs-extensions]: Cannot call `response.sendToStream()` without calling `response.transform()` first')
```

2021-12-13 21:37 UTC, isocroft commented on providers/ResponseExtensionProvider.js
> +      }
```suggestion
      if (!this.isPending || this.response.finished) {
        this.__hasSentResponse = true
        this._canStream = false
        return this
      }
```

2021-12-13 21:37 UTC, isocroft commented on providers/ResponseExtensionProvider.js
> +        this.__stream.nextChunk = payload
```suggestion
            this.__stream.nextChunk = Buffer.from('\r\n', 'ascii')
          } else {
            this.__stream.nextChunk = Buffer.from(`${payload.length}\r\n`, 'ascii')
          }
        }

        this.__stream.nextChunk = payload
```

2021-12-13 21:37 UTC, isocroft commented on providers/ResponseExtensionProvider.js
> +          this.__stream.nextChunk = `\r\n`
```suggestion
          this.__stream.nextChunk = Buffer.from('0\r\n', 'ascii')
          this.__stream.nextChunk = Buffer.from('\r\n', 'ascii')
```

2021-12-13 21:37 UTC, isocroft commented on providers/ResponseExtensionProvider.js
> +          error => that.abortIf(true, error.code === 'ENOENT' ? 404 : 500, `Something unexpected happened: ${error.message}`)
```suggestion
          error => that.abortIf(error !== null, error.code === 'ENOENT' ? 404 : 500, `Something unexpected happened: ${error.message}`)
```

2021-12-13 21:37 UTC, isocroft commented on providers/ResponseExtensionProvider.js
> +          return false
```suggestion
          return this._canStream
```

2021-12-13 21:37 UTC, isocroft commented on providers/ResponseExtensionProvider.js
> +      return true
```suggestion
      return this._canStream
```

2021-12-13 21:37 UTC, isocroft commented on providers/ResponseExtensionProvider.js
> +            : null
```suggestion
            : -1
```

2021-12-13 21:37 UTC, isocroft commented on providers/ResponseExtensionProvider.js
> +            while (null !== (chunk = this.nextChunk)) {
```suggestion
            while (-1 !== (chunk = this.nextChunk)) {
```

2021-12-13 21:37 UTC, isocroft commented on providers/ResponseExtensionProvider.js
> +        const data = notJson || typeof body !== 'object' ? String(body) : safeStringify(body)
```suggestion
        let data = null
        if (!(body instanceof Buffer) {
          if (typeof body === 'object' && notJson) {
            data = String(body)
          }

          if (!notJson) {
            data = safeStringify(body)
          }
        }
```

2021-12-13 21:37 UTC, isocroft commented on providers/ResponseExtensionProvider.js
> +    Response.macro('transform', function (encoding = 'utf8', chunked = false, multipart = false) {
```suggestion
    Response.macro('transform', function (encoding = 'utf8', { chunked = false, multipart = false }) {
```

2021-12-13 21:37 UTC, isocroft commented on providers/ResponseExtensionProvider.js
> +    Response.macro('sendToStream', (body) => {
```suggestion
    Response.macro('sendToStream', (body, multiPartContentType = 'text/plain; charset=utf-8') => {
```

2021-12-13 21:37 UTC, isocroft commented on providers/ResponseExtensionProvider.js
> +        this.__emitter.emit('adonisjs_stream_data', { body, notJson: isNotJSONRequest })
```suggestion
        this.__emitter.emit('adonisjs_stream_data', {
          body,
          notJson: isNotJSONRequest,
          contentType: multiPartContentType
        })
```

2021-12-13 21:37 UTC, isocroft commented on providers/ResponseExtensionProvider.js
> +      this.__emitter.on('adonisjs_stream_data', ({ body, notJson }) => {
```suggestion
      this.__emitter.on('adonisjs_stream_data', ({ body, notJson, contentType }) => {
```

2021-12-13 21:37 UTC, isocroft commented on providers/ResponseExtensionProvider.js
> +            )
```suggestion
            this.__stream.nextChunk = Buffer.concat([
              Buffer.from(`\r\n--${this.multiPartBoundary}\r\n`, 'ascii'),
              Buffer.from(`Content-Type: ${contentType}\r\n`, 'ascii'),
              Buffer.from(`Content-Length: ${payload.length}\r\n\r\n`, 'ascii'),
```

2021-12-13 21:37 UTC, isocroft commented on providers/ResponseExtensionProvider.js
> +      setImmediate(() => {
```suggestion
      const compressionAlgo = this.Config.get('app.http.compression.algo')

      if (multipart) {
        this.multiPartBoundary = Number(1 + Math.random() * 234567890).toString(16).replace('.', Date.now())
        this.safeHeader('Content-Type', `multipart/x-mixed-replace; boundary="${this.multiPartBoundary}"`)
      }

      setImmediate(() => {
```

2021-12-13 22:57 UTC, isocroft commented on providers/ResponseExtensionProvider.js
> +            this.__stream.nextChunk = Buffer.from('\r\n', 'ascii')
```suggestion
            ])
```

2021-12-13 22:57 UTC, isocroft commented on providers/ResponseExtensionProvider.js
> +        if (Encoding.includes(String(compressionAlgo))) {
```suggestion
        if (compressionIsEnabled && Encoding.includes(String(compressionAlgo))) {
```

2021-12-13 22:57 UTC, isocroft commented on providers/ResponseExtensionProvider.js
> +        if (TransferEncoding.includes(String(compressionAlgo))) {
```suggestion
        if (compressionIsEnabled && TransferEncoding.includes(String(compressionAlgo))) {
```

2021-12-13 23:34 UTC, isocroft commented on providers/ResponseExtensionProvider.js
> +        this.safeHeader('Content-Type', `multipart/x-mixed-replace; boundary="${this.multiPartBoundary}"`)
```suggestion
        this.safeHeader('X-Accel-Buffering', 'no')
        this.safeHeader('Content-Type', `multipart/x-mixed-replace; boundary="${this.multiPartBoundary}"`)
```

2021-12-13 23:34 UTC, isocroft commented on providers/ResponseExtensionProvider.js
> +              Buffer.from(`\r\n--${this.multiPartBoundary}\r\n`, 'ascii'),
```suggestion
              Buffer.from(`${ isFirstMultipartBlock ? '\r\n' : ''}--${this.multiPartBoundary}\r\n`, 'ascii'),
```

2021-12-13 23:34 UTC, isocroft commented on providers/ResponseExtensionProvider.js
> +            this.__stream.nextChunk = Buffer.concat([
```suggestion
            const isFirstMultipartBlock = this.__stream._backPressureQueue.length === 0
            this.__stream.nextChunk = Buffer.concat([
```

2021-12-14 11:47 UTC, isocroft commented on providers/ResponseExtensionProvider.js
> +const { Readable } = reequire('stream');
```suggestion
const { Readable } = require('stream');
const onFinished = require('on-finished')
```

2021-12-14 11:49 UTC, isocroft commented on providers/ResponseExtensionProvider.js
> +    Response.macro('transform', function (encoding = 'utf8', { chunked = false, multipart = false }) {
```suggestion
    Response.macro('transform', function (encoding = 'utf8', { chunked, multipart }) {
```

2021-12-14 11:54 UTC, isocroft commented on providers/ResponseExtensionProvider.js
> +        encoding.replace(/^us-/, '')
```suggestion
```

2021-12-14 12:24 UTC, isocroft commented on providers/ResponseExtensionProvider.js
> +          }
```suggestion
          let chunk = null
          while (-1 !== (chunk = this.nextChunk)) {
            const pushed = this.push(chunk)
            if (!pushed) {
              break;
            }
          }
```

2021-12-14 21:29 UTC, isocroft commented on providers/ResponseExtensionProvider.js
> +        this.safeHeader('Content-Type', `multipart/x-mixed-replace; boundary="${this.multiPartBoundary}"`)
```suggestion
        this.safeHeader('X-Accel-Buffering', 'no')
        this.safeHeader('Cache-Control', 'no-cache, max-age=0, private')
        this.safeHeader('Pragma', 'no-cache')
        this.safeHeader('Age', '0')
        this.safeHeader('Content-Type', `multipart/x-mixed-replace; boundary="${this.multiPartBoundary}"`)
```

2021-12-15 15:57 UTC, stitchng requested changes

2021-12-15 15:57 UTC, stitchng commented on providers/ResponseExtensionProvider.js
> +        const payload = data instanceof Buffer ? data : Buffer.from(data, encoding.replace(/^us-/, ''))
```suggestion

          const isJson = !notJson

          if (isJson) {
            data = safeStringify(body)
          }
        }

        const payload = data instanceof Buffer ? data : Buffer.from(data, encoding.replace(/^us-/, ''))
```

2021-12-15 16:04 UTC, merged