chore: update instructions file
stitchng/adonis-extensions pull request #21
Opened 2021-12-11 06:44 UTC by isocroft

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce?

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](https://github.com/stitchng/adonis-extensions/blob/master/CONTRIBUTING.md) doc
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2021-12-13 22:18 UTC, isocroft commented on instructions.md
> +  'Adonis/Middleware/StreamResponseBody', // optional
```suggestion
```

2021-12-13 22:18 UTC, isocroft commented on instructions.md
> +
```suggestion
## Using NodeJS Streams (HTTP Streaming / Compression)

>You have to include the `stream` named middleware (and optionally set AdonisJS middleware arguments: `stream: chunked, multipart`) to utilise **NodeJS Streams** on the route you wish to enable HTTP streaming and/or HTTP compression. The `chunkedResponse` config in _config/extensions.js_ is used only for app-level configurations while the middleware argument is used for route-level configurations.

```js

const Route = use('Route')

Route.get('/timestamp', function ({ response }) {
  response.sendToStream({ time: Date.now() })
}).middleware(['auth', 'stream:chunked']).as('app.timestamping')
```

2021-12-13 22:22 UTC, isocroft commented on instructions.md
> +const Route = use('Route')
```suggestion

/** @type {typeof import('@adonisjs/framework/src/Route/Manager')} */
const Route = use('Route')
```

2021-12-13 22:22 UTC, isocroft commented on instructions.md
> +}).middleware(['auth', 'stream:chunked']).as('app.timestamping')
```suggestion
}).middleware(['auth', 'stream:chunked']).as('app.timestamping')
```

```

2021-12-15 13:55 UTC, stitchng requested changes

2021-12-15 13:55 UTC, stitchng commented on instructions.md
> +  'Adonis/Middleware/UpdateViewData',
```suggestion
  'Adonis/Middleware/UpdateViewData'
```

2021-12-15 13:55 UTC, stitchng commented on instructions.md
>  The configuration is saved inside `config/extension.js` file. Tweak it accordingly.
```suggestion
The configuration for this package is saved inside `config/extension.js` file. Tweak it according to your preference. Also, you will need to update the `config/app.js` file to include a section for HTTP compression configuration. This section should go under the `http` sub key and be title `compression` as depicted below:
```

2021-12-15 13:55 UTC, stitchng commented on instructions.md
> +    | response.transform('ascii').sendToStream(Date.now())
```suggestion
    | response.transform('ascii', { chunked: false, multipart: false }).sendToStream(Date.now())
```

2021-12-15 13:55 UTC, stitchng commented on instructions.md
> +}).middleware(['auth', 'stream:chunked']).as('app.timestamping')
```suggestion
  response.sendToStream({ time: Date.now() }, 'application/json; charset=utf-8')
}).middleware(['auth', 'stream: chunked, mutipart']).as('app.timestamping')

Route.post('/random', function ({ response }) {
  response.sendToStream(Math.random() * 12345)
}).middleware('auth', 'stream: chunked']).as('app.random')
```

2021-12-15 14:31 UTC, stitchng requested changes

2021-12-15 14:31 UTC, stitchng commented on instructions.md
> +}).middleware('auth', 'stream: chunked']).as('app.random')
```suggestion
}).middleware(['stream: chunked']).as('app.randoming')
```

2021-12-15 14:31 UTC, stitchng commented on instructions.md
> +
```suggestion

As it concerns **AdonisJS** 4, [NodeJS Streams](https://nodesource.com/blog/understanding-streams-in-nodejs/) are only used when files (usually on disk) are to be sent to the (HTTP) client (e.g. web, mobile) via either the `response.download()` or `response.attachment()` methods (on the AdonisJS response objects).  This has made it such that dynamically-created data (e.g. from a database as JSON) that is large enough can't utilize [NodeJS Streams](https://nodesource.com/blog/understanding-streams-in-nodejs/). Now, with **adonisjs-extensions**, you can wield the power of [NodeJS Streams](https://nodesource.com/blog/understanding-streams-in-nodejs/) while sending dynamically-created data to the (HTTP) client without any hindrance.

Below is how to get started using NodeJS streams:

```

2021-12-15 14:35 UTC, merged